sudo: false
language: java
jdk:
- openjdk8
branches:
  except:
    - /.*wip.*/i
script: "mvn clean verify"
after_success:
- "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ] && mvn deploy -DskipTests --settings ./deploy-settings.xml"
cache:
  directories:
    - $HOME/.m2/repository
